; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

[env:indoor]
build_flags      = -I include -D INDOOR_AGENT
build_src_filter = -<*> +<indoor_main.cpp>

[env:outdoor]
build_flags      = -I include -D OUTDOOR_AGENT
build_src_filter = -<*> +<outdoor_main.cpp>
